#cloud-config
groups:
  - docker

users:
- default
- name: hpe
  lock_passwd: true
  shell: /bin/bash
  ssh-authorized-keys:
    - ${ssh_public_key}
  groups: [docker]
  sudo: ["ALL=(ALL) NOPASSWD:ALL"]


packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

write_files:
- content: |-
    [Unit]
    Description=Ezmeral as a service
    Requires=docker.service
    After=docker.service

    [Service]
    Restart=on-failure
    RestartSec=10
    ExecStart=/usr/bin/docker run 
    ExecStop=-/usr/bin/docker stop -t 2 %p

    [Install]
    WantedBy=multi-user.target
  owner: root:root
  path: /etc/systemd/system/ezmeral.service
  permissions: '0644'


runcmd:
  - apt-get update -y
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl daemon-reload
  - systemctl enable docker --now
  - systemctl enable ezmeral --now
  - mkdir /jaideep
  - curl -O https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh
  - chmod +x openvpn-install.sh
  - AUTO_INSTALL=y ./openvpn-install.sh
  - export MENU_OPTION="1"
  - export CLIENT="foo"
  - export PASS="1"
  - ./openvpn-install.sh
  - sudo cp /root/client.ovpn /tmp/client.ovpn
  - sudo mkdir /nfsroot
  - mkdir /tmp/jaideep

final_message: "The system is finally up, after $UPTIME seconds"
